### ISSUE TITLE
How to access raw soundstream data from input?

### ISSUE THREAD

**Issue by polyclick** [npisanti/ofxPDSP#5] opened 2016-09-10 10:21 UTC
Hi

I really like this library, I've been patching some devices to generate some sounds but I'm still struggling how to link my own audio analyzer to one of the ofxPDSP inputs. I think I'm missing something to continue. Can you help out?

I've created my own AudioAnalyzer class that analyzes the raw float data from an ofSoundStream. But since ofxPDSP registers both an input and output stream, I need to be able to get the raw float data from the inputStream in ofxPDSP (it's currently a private variable).

Normally I do this:

```
  // setup audio device input
  soundStream.setDeviceID(AUDIO_IN_DEVICE_ID);
  soundStream.setup(NUM_CHANNELS_OUT, NUM_CHANNELS_IN, SAMPLE_RATE, BUFFER_SIZE, NUM_BUFFERS);
  soundStream.setInput(this);

  // analyzer setup
  audioAnalyzer = new AudioAnalyzer();
  audioAnalyzer->setup(&soundStream);
```

and then I pass the float data to my analyzer like this:

```
void AudioManager::audioIn(float *input, int bufferSize, int nChannels) {
  audioAnalyzer->analyze(input, bufferSize, nChannels);
}
```

But now I'm using ofxPDSP for both in and output:

```
  // setup the audio output engine
  engine = new ofxPDSPEngine();
  engine->setDeviceID(AUDIO_DEVICE_ID);
  engine->setup(SAMPLE_RATE, BUFFER_SIZE, NUM_BUFFERS);
```

But how do I link the input of ofxPDSP to my audio analyzer? I can't seem to access the raw input data. Do I need to pass the audio_in through another device or something?

Thanks for your help!

**Comment by npisanti** [comment] 2016-09-11 09:52
if you don't need to process input in ofxPDSP before starting the engine you can use

> `engine.setChannels( 0, 2 );`

(0 input channels, 2 output channels, if you use more outputs change it). This won't open any input stream for ofxPDSP so you are free to use the input device as you wish. 

For an easy API for custom sound processing you could try to extend pdsp::Formula http://npisanti.com/ofxPDSP/classpdsp_1_1_formula.html

I'm also thinking about making another abstract class with a `audioIn(float *input, int bufferSize, int nChannels) ` method to overload to make more easily to integrate other addons inside ofxPDSP

**Comment by polyclick** [comment] 2016-09-11 18:13
I tried your suggestion with the channel count but this hangs my application. I think there's a conflict somewhere in a low level api that locks the input stream.

I want to use the same device (audio card with 10 inputs & 10 outputs) for both input & output (i only need 2 channels in and 2 channels out).

This is my current setup:

```
  // setup audio device input
  soundStream.setDeviceID(AUDIO_IN_DEVICE_ID);
  soundStream.setup(0, NUM_CHANNELS_IN, SAMPLE_RATE, BUFFER_SIZE, NUM_BUFFERS);
  soundStream.setInput(this);
  
  
  
  // setupe the audio output engine
  engine = new ofxPDSPEngine();
  engine->setChannels(0, NUM_CHANNELS_OUT);
  engine->setDeviceID(AUDIO_OUT_DEVICE_ID);
  engine->setup(SAMPLE_RATE, BUFFER_SIZE, NUM_BUFFERS);
```

Where const are:

```
  const int AUDIO_IN_DEVICE_ID    = 2;      // id of the input device
  const int AUDIO_OUT_DEVICE_ID   = 2;      // id of the output device
  const int NUM_CHANNELS_OUT      = 2;
  const int NUM_CHANNELS_IN       = 2;
  const int SAMPLE_RATE           = 44100;
  const int BUFFER_SIZE           = 512;
  const int NUM_BUFFERS           = 4; 
```

**Comment by npisanti** [comment] 2016-09-12 14:54
please don't use the ofxPDSP classes using dynamic allocation, they're all programmed to be used in a RAII way, and they are never used like this in the examples (but maybe i have to state it more clearly somewhere). 
I tested your code and i also had some problems (but they weren't caused by your use of a pointer for ofxPDSPEngine), i think that when two ofSoundStreams execute an audio callback at the same time on the same device strange things can happen, so i will implement a class for easy integration of other addons as soon as possible ( i think next week ). In the meanwhile if you are in an hurry and analyzing a single channel or two channels using two analyzer can be good enough you can try extend pdsp::Formula this way (add your audioAnalyzer variable and other things):
```

class AnalyzerWrapper : public pdsp::Formula {

    float formula(const float & x) noexcept override {};

    void formulaAudioRate(float* &output, const float* &input, const int &bufferSize) noexcept override {
        audioAnalyzer->analyze(input, bufferSize, 1);
    }

}
```
then create an `AnalyzerWrapper` variable `analyzerWrapper` in your `ofApp.h `and patch it like this:

`engine.audio_in(0) >> analyzerWrapper >> engine.blackhole();`

**Comment by npisanti** [comment] 2016-09-16 19:01
i've just added a new class for integrating other addons inside ofxPDSP, called ofxPDSPWrapper. There is also an example to show how to use it, i've made it by porting the standard oF audioInputExample, check it out

**Comment by npisanti** [comment] 2016-09-29 21:31
it seems there are no problems, i'll close this issue!

**Closed by npisanti** 2016-09-29 21:31 UTC
