### ISSUE TITLE
undefined reference to SynthVoice::synthUI on example-midi_polysynth

### ISSUE THREAD

**Issue by hamoid** [npisanti/ofxPDSP#2] opened 2016-03-10 11:22 UTC
Hi! I try to compile the midi_polysynth example on QTCreator with openFrameworks 0.9.3 (from GitHub) and I get:

    /home/xxx/src/openFrameworks/addons/ofxPDSP/example-midi_polysynth/src/ofApp.cpp:73: error: undefined reference to `SynthVoice::synthUI'

Did I do something wrong, or is there a bug somewhere? Cheers!

**Comment by ukelady** [comment] 2016-03-10 18:21
I also failed to build it with XCode. But failed with different issue. I've posted on oF forum:
https://forum.openframeworks.cc/t/compilation-errors-in-ofparameter-h/22708

**Comment by nightshining** [comment] 2016-03-11 16:19
I think my issue is similar enough so I'm posted here as well. Building midi_polysynth as is in examples folder, on OF release 0.9.1 getting the following error.
![screen shot 2016-03-11 at 11 18 31 am](https://cloud.githubusercontent.com/assets/6088743/13708175/2c710ac2-e77b-11e5-93f6-dd48b4e76e20.png)

**Comment by npisanti** [comment] 2016-03-12 17:40
i've made some changes to example-midi_polysynth that should fix both issues. It seems that ofParameterGroup  was not behaving well when initialized in a static variable (SynthVoice::synthUI), and when you need to use ofParameter in a synth class you have to include "ofMain.h" (this is really strange as i put the necessary ifndef guards in the ofxPDSPParameter class).

Let me know if i can close the issue (and also for people that are using QTCreator let me know your platform / platform version / QTCreator version if the issue is not resolved).

**Comment by ukelady** [comment] 2016-03-12 18:40
Thanks for your reply! I just added "include "ofMain.h"" to voice.h. But
unfortunately it still doesn't work. I've attached two screen shots.

**Comment by ukelady** [comment] 2016-03-12 19:06
Sorry, I just realize the changes are more than one line :)

I've updated my local project and it's working :)

Thanks!!!

**Comment by npisanti** [comment] 2016-03-12 19:13
@ukelady  perfect! can you try also downloading ofxPDSP again and seeing if the updated example is working on your platform?

**Comment by ukelady** [comment] 2016-03-12 20:59
Yes I downloaded the latest version and it works.

Unfortunately Polyphony have a few issues. I'll report in a separate thread.

**Comment by hamoid** [comment] 2016-03-12 21:09
After pulling all changes, the HelloWorld and Graincloud examples do work fine, but the midi-polysynth gives me this error:

![2016-03-12-215856_937x770_scrot](https://cloud.githubusercontent.com/assets/108264/13725328/8644e6e4-e89e-11e5-84e8-7e444c96c51a.png)

I'm on Linux 64bit.

**Comment by npisanti** [comment] 2016-03-12 22:21
i think there could be a problem in the way qtcreator is importing the projects, i've tested it now with qt5.5 on Debian 64bit and it is not showing voice.h and voice.cpp and giving me the same errors. The same example is successfully build by the command line, could you try just using "make Debug" or "make Release"?

**Comment by npisanti** [comment] 2016-03-12 22:28
@hamoid  also try importing the project using the project generator instead of the openFramework qtcreator template, i was able to successfully build the example after updating it with the projectGenerator

**Comment by hamoid** [comment] 2016-03-13 09:43
@npisanti ```make Debug``` works. Thank you! I'll mention the qtcreator template issue to the authors :)

**Comment by npisanti** [comment] 2016-04-08 16:10
I'm closing this as it is not a ofxPDSP issues, but a QtCreator one. Also the original example is a bit different in the latest release.

**Closed by npisanti** 2016-04-08 16:10 UTC
